services:
  db:
    image: postgres:16
    container_name: labelling-db-uat
    env_file:
      - .env.uat
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - db-data-uat:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}'
    container_name: labelling-backend-uat
    env_file:
      - .env.uat
      - backend/.env.uat
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}'
    ports:
      - '3001:3000'
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    container_name: labelling-frontend-uat
    env_file:
      - .env.uat
      - frontend/.env.uat
    environment:
      VITE_BASE_URL: 'http://192.168.20.180:3001'
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  db-data-uat:
