services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecus5
      MYSQL_USER: ecus5
      MYSQL_PASSWORD: ecus5
    volumes:
      - mysql_prod:/var/lib/mysql

  backend:
    build:
      context: ./backend
      target: prod
    restart: always
    environment:
      DATABASE_URL: mysql://ecus5:ecus5@mysql:3306/ecus5
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      target: runtime
    restart: always
    ports:
      - "80:80"

volumes:
  mysql_prod:
