version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: ecus5-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ecus5
      MYSQL_USER: ECUS5
      MYSQL_PASSWORD: ecus5
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: ecus5-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://ECUS5:ecus5@mysql:3306/ecus5
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "npx prisma db push && npm start"

volumes:
  mysql_data:
