services:
  db:
    image: postgres:16
    container_name: labelling-db-prod
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5435:5432'
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    networks:
      - labnet

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      args:
        DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}'
    container_name: labelling-backend-prod
    env_file:
      - .env.prod
      - backend/.env.prod
    depends_on:
      - db
    networks:
      - labnet
    ports:
      - '3000:3000'
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    container_name: labelling-frontend-prod
    env_file:
      - .env.prod
      - frontend/.env.prod
    networks:
      - labnet
    expose:
      - '80'
    ports:
      - '5173:80'
    restart: unless-stopped

volumes:
  db-data-prod:

networks:
  labnet:
    driver: bridge
