name: Deploy ECUS5 - DEV (Self-hosted)

on:
  push:
    branches: ['develop']
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy ECUS5 DEV
    runs-on: [self-hosted, dev]

    env:
      ENV: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Docker
        run: |
          docker --version
          docker compose version
      - name: Create env files from GitHub Secrets
        run: |
          echo "${{ secrets.ENV_DEV_ROOT }}" > .env.dev

          mkdir -p backend frontend

          echo "${{ secrets.ENV_DEV_BACKEND }}" > backend/.env.dev
          echo "${{ secrets.ENV_DEV_FRONTEND }}" > frontend/.env.dev
      - name: Stop old containers
        run: |
          docker compose \
            --env-file .env.dev \
            -f docker-compose.dev.yml \
            down
      - name: Build & start containers
        run: |
          docker compose \
            --env-file .env.dev \
            -f docker-compose.dev.yml \
            up -d --build
      - name: Prisma migrate (DEV)
        run: |
          docker compose \
            -f docker-compose.dev.yml \
            exec backend \
            npx prisma migrate deploy
      - name: Cleanup unused images
        run: docker image prune -f
