name: Deploy ECUS5 - UAT

on:
  push:
    branches: [uat]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, uat]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Runner info
        run: |
          hostname
          docker --version
          docker compose version

      - name: Deploy UAT containers
        run: |
          docker compose -f docker-compose.uat.yml down
          docker compose -f docker-compose.uat.yml up -d --build

      - name: Docker status
        run: docker ps
