name: Deploy ECUS5 - DEV (Self-hosted)

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Runner info
        run: |
          echo "Host:"
          hostname
          echo "Path:"
          pwd
          docker --version
          docker compose version

      - name: Stop old containers
        run: |
          docker compose -f docker-compose.dev.yml down

      - name: Build & Deploy DEV
        run: |
          docker compose -f docker-compose.dev.yml up -d --build

      - name: Check running containers
        run: |
          docker ps
